### PR TITLE
Update tasks.js

### LINKED ISSUE #26: Feature request: yarn install (if yarn is installed)
I have a project and instead of yarn npm is used. SO please check not if yarn is installed but instead check if `yarn.lock` file is present.

### PR DESCRIPTION
**Pull request by FDiskas**
Added `npm ci` task and respect yarn

Closes #26

### CODE REVIEW

**Comment by pmadruga** [comment]
Thanks! I'll take a look as soon as possible.

**Comment by FDiskas** [comment]
Keep in mind that I did not test it.
Thanks

**Comment by FDiskas** [comment]
Any news?

**Comment by pmadruga** [comment]
I haven't had the time to test it yet. Life is a bit in the way right now but will do my best to review this quickly.

**Pull request merged**
